apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    grafana/overview-dashboard: https://grafana.local.lan.vernal.dev/d/_KEgCD1Gz/kubernetes?orgId=1
  links:
  {% for component in values.components %}
  - title: ${{ component }}
    url: ${{ component }}-${{ values.name }}-${{ values.owner | replace(":", "-") | replace("/", "-") }}-app.local.lan.vernal.dev
  {% endfor %}
spec:
  type: service
  owner: ${{ values.owner | dump }}
  lifecycle: experimental

